module Stopwatch(
    input  [4:0] sw,   // binary input from switches
                       // sw[4] and sw[3] are turbo mode, sw[2] is slow mode
                       // sw[1] toggles display, sw[0] is stopwatch enable
    input        btnC, // push button being used as reset
    input        clk,  // 100 MHz clock generated by Basys 3
    output [6:0] seg,  // segments
    output [3:0] an,   // display specific anodes
    output       dp    // display specific decimal points
);

wire       clk_5MHz, clk_100Hz;

wire [3:0] currentDigit;
wire [3:0] centisec;
wire [3:0] decisec;
wire [3:0] sec;
wire [3:0] tensec;
wire [3:0] min;
wire [3:0] tenmin;

wire [5:0] enable;
wire [5:0] clear;

wire       dpEnable;

// module instantiation: YOU SHOULD NOT HAVE TO EDIT ANY OF THIS

clk_wiz_0 dividerA(clk_5MHz, clk);
ClockDivider dividerB(clk_5MHz, btnC, sw[4:3], sw[2], clk_100Hz);

DisplayRotator dispRot(clk_5MHz, sw[1], centisec, decisec, sec, tensec, min, tenmin, an, dpEnable, currentDigit);
BCDToLED bcdConverter(currentDigit, seg, );

Counter myCounterCS(clk_100Hz, btnC, enable[0], clear[0], centisec);
Counter myCounterDS(clk_100Hz, btnC, enable[1], clear[1], decisec);
Counter myCounterS(clk_100Hz, btnC, enable[2], clear[2], sec);
Counter myCounterTS(clk_100Hz, btnC, enable[3], clear[3], tensec);
Counter myCounterM(clk_100Hz, btnC, enable[4], clear[4], min);
Counter myCounterTM(clk_100Hz, btnC, enable[5], clear[5], tenmin);


// enable/clear logic: YOU NEED TO IMPLEMENT THESE

assign enable[0] = sw[0];
assign enable[1] = (centisec == 9);
assign enable[2] = (centisec == 9) & (decisec == 9);
assign enable[3] = (centisec == 9) & (decisec == 9) & (sec == 9);
assign enable[4] = (centisec == 9) & (decisec == 9) & (sec == 9) & (tensec == 5);
assign enable[5] = (centisec == 9) & (decisec == 9) & (sec == 9) & (tensec == 5) & (min == 9);

assign clear[0] = (centisec == 9 & enable[0]);
assign clear[1] = (decisec == 9 & enable[1]);
assign clear[2] = (sec == 9 & enable[2]);
assign clear[3] = (tensec == 5 & enable[3]);
assign clear[4] = (min == 9 & enable[4]);
assign clear[5] = (tenmin == 5 & enable[5]);


// decimal point logic: YOU SHOULD NOT NEED TO EDIT THIS

assign dp = dpEnable | (decisec < 4'd5);


endmodule